### ISSUE TITLE
Counties appearing multiple times in county-returns tables

### ISSUE THREAD

**Issue by DanielKim1** [mapping-elections/elections-data#71]
8th Congress, VA
kys_jefferson and wvs_jefferson have the same votes, vote percentages, etc.
(These counties were already added to congressional-counties-parties.csv so pull request #70 is affected by this issue).

9th Congress, VA
kys_jefferson and wvs_jefferson (district 2)
kys_madison and vas_madison (district 10)
kys_mason and wvs_mason (district 5)
all have the same votes, vote percentages, etc.

**Comment by lmullen** [comment]
This was my mistake (probably). Because of a special case where Virginia has a lot of counties that later became parts of other states, the export scripts include VA, WV, and KY counties. I didn't realize that there is, e.g., both a WV and a KY Jefferson county. So they got duplicated in the data. There was no ill effect on the map since they don't get joined to the data, but @jfbratt deleted them from the data for correctness.
